gauge_instances = {};
(function(gauge_instances){
    var gauges_configs = [
        {
            id: "throttle",
            meta: {
                width: 200,
                height: 200,
                units: "%",
                minValue: -1,
                startAngle: 45,
                ticksAngle: 270,
                valueBox: false,
                maxValue: 1,
                majorTicks: [
                    "-100",
                    "-80",
                    "-60",
                    "-40",
                    "-20",
                    "0",
                    "20",
                    "40",
                    "60",
                    "80",
                    "100"
                ],
                minorTicks: 2,
                strokeTicks: true,
                highlights: [
                    {
                        "from": 0.8,
                        "to": 1.0,
                        "color": "rgba(200, 50, 50, .75)"
                    },
                    {
                        "from": -1.0,
                        "to": -0.8,
                        "color": "rgba(200, 50, 50, .75)"
                    }
                ],
                colorPlate: "#fff",
                borderShadowWidth: 0,
                borders: false,
                needleType: "arrow",
                needleWidth: 2,
                needleCircleSize: 7,
                needleCircleOuter: true,
                needleCircleInner: false,
                animationDuration: 100,
                animationRule: "linear"
            }
        },
        {
            id: "direction",
            meta: {
                width: 200,
                height: 200,
                units: "degree",
                minValue: 0,
                startAngle: 90,
                ticksAngle: 180,
                valueBox: false,
                maxValue: 180,
                majorTicks: [
                    "0",
                    "20",
                    "40",
                    "60",
                    "80",
                    "100",
                    "120",
                    "140",
                    "160",
                    "180"
                ],
                minorTicks: 2,
                strokeTicks: true,
                colorPlate: "#fff",
                borderShadowWidth: 0,
                borders: false,
                needleType: "arrow",
                needleWidth: 2,
                needleCircleSize: 7,
                needleCircleOuter: true,
                needleCircleInner: false,
                animationDuration: 100,
                animationRule: "linear"
            }
        },
        {
            id: "compass",
            meta: {
                width: 200,
                height: 200,
                minValue: 0,
                maxValue: 360,
                majorTicks: [
                    "N",
                    "NE",
                    "E",
                    "SE",
                    "S",
                    "SW",
                    "W",
                    "NW",
                    "N"
                ],
                minorTicks: 22,
                ticksAngle: 360,
                startAngle: 180,
                strokeTicks: false,
                highlights: false,
                colorPlate: "#a33",
                colorMajorTicks: "#f5f5f5",
                colorMinorTicks: "#ddd",
                colorNumbers: "#ccc",
                colorNeedle: "rgba(240, 128, 128, 1)",
                colorNeedleEnd: "rgba(255, 160, 122, .9)",
                valueBox: false,
                valueTextShadow: false,
                colorCircleInner: "#fff",
                colorNeedleCircleOuter: "#ccc",
                needleCircleSize: 15,
                needleCircleOuter: false,
                animationRule: "linear",
                needleType: "line",
                needleStart: 75,
                needleEnd: 99,
                needleWidth: 3,
                borders: true,
                borderInnerWidth: 0,
                borderMiddleWidth: 0,
                borderOuterWidth: 10,
                colorBorderOuter: "#ccc",
                colorBorderOuterEnd: "#ccc",
                colorNeedleShadowDown: "#222",
                borderShadowWidth: 0,
                animationTarget: "plate",
                value: 0,
                animateOnInit: true
            }
        },
        {
            id: "wind_direction",
            meta: {
                width: 200,
                height: 200,
                minValue: 0,
                maxValue: 360,
                majorTicks: [
                    "N",
                    "NE",
                    "E",
                    "SE",
                    "S",
                    "SW",
                    "W",
                    "NW",
                    "N"
                ],
                minorTicks: 22,
                ticksAngle: 360,
                startAngle: 180,
                strokeTicks: false,
                highlights: false,
                colorPlate: "#a33",
                colorMajorTicks: "#f5f5f5",
                colorMinorTicks: "#ddd",
                colorNumbers: "#ccc",
                colorNeedle: "rgba(240, 128, 128, 1)",
                colorNeedleEnd: "rgba(255, 160, 122, .9)",
                valueBox: false,
                valueTextShadow: false,
                colorCircleInner: "#fff",
                colorNeedleCircleOuter: "#ccc",
                needleCircleSize: 15,
                needleCircleOuter: false,
                animationRule: "linear",
                needleType: "line",
                needleStart: 75,
                needleEnd: 99,
                needleWidth: 3,
                borders: true,
                borderInnerWidth: 0,
                borderMiddleWidth: 0,
                borderOuterWidth: 10,
                colorBorderOuter: "#ccc",
                colorBorderOuterEnd: "#ccc",
                colorNeedleShadowDown: "#222",
                borderShadowWidth: 0,
                animationTarget: "plate",
                value: 0,
                animateOnInit: true
            }
        },
        {
            id: "heading",
            meta: {
                width: 200,
                height: 200,
                minValue: 0,
                maxValue: 360,
                majorTicks: [
                    "N",
                    "NE",
                    "E",
                    "SE",
                    "S",
                    "SW",
                    "W",
                    "NW",
                    "N"
                ],
                minorTicks: 22,
                ticksAngle: 360,
                startAngle: 180,
                strokeTicks: false,
                highlights: false,
                colorPlate: "#a33",
                colorMajorTicks: "#f5f5f5",
                colorMinorTicks: "#ddd",
                colorNumbers: "#ccc",
                colorNeedle: "rgba(240, 128, 128, 1)",
                colorNeedleEnd: "rgba(255, 160, 122, .9)",
                valueBox: false,
                valueTextShadow: false,
                colorCircleInner: "#fff",
                colorNeedleCircleOuter: "#ccc",
                needleCircleSize: 15,
                needleCircleOuter: false,
                animationRule: "linear",
                needleType: "line",
                needleStart: 75,
                needleEnd: 99,
                needleWidth: 3,
                borders: true,
                borderInnerWidth: 0,
                borderMiddleWidth: 0,
                borderOuterWidth: 10,
                colorBorderOuter: "#ccc",
                colorBorderOuterEnd: "#ccc",
                colorNeedleShadowDown: "#222",
                borderShadowWidth: 0,
                animationTarget: "plate",
                value: 0,
                animateOnInit: true
            }
        }
    ]

    gauges_configs.forEach(function(gauge_config){
        gauge_config.meta.renderTo = gauge_config.id;
        gauge = new RadialGauge(gauge_config.meta);
        gauge.draw();
        gauge_instances[gauge_config.id] = gauge;
    })
})(gauge_instances)